### ISSUE TITLE
"SPARKFUN ESP32 THING" ISSUE WITH ESPRESSIF VERSION 3.0.0 - CORE CLOCK INCORRECT FREQUENCY?

### ISSUE THREAD

**Issue by dfrodin** [sparkfun/ESP32_Thing_Plus#7]
This applies to the "Sparkfun ESP32 Thing" not the Thing Plus.

With the latest 3.0.0 rev of the espressif ESP32 library with the Arduino IDE there is an issue with several of the clocks or perhaps just the core clock.

I initialize the serial port to 115k baud in setup(). With the latest espressif library change I have to reduce the baud rate on the serial monitor to 74880 to get meaningful output. The ratio of those two values is 115200/74880 = 1.55.

I noticed that pressing the reset button on the "ESP32 Thing" produces the normal output of ...
ets Jul 29 2019 12:21:46
rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:1288
load:0x40078000,len:13872
load:0x40080400,len:4
ho 8 tail 4 room 4
load:0x40080404,len:3048
entry 0x40080590

This output arrives at the correct 115200 baud rather than the runtime baudrate of 74880.

If I output a message every 60,000 msec using the Arduino millis() function you should get a message output every minute.
This has worked in the past but now outputs a message every 1 min 33 seconds. The ratio of these values is also 93/60 = 1.55.

I haven't been able to reproduce these problems on a XIAO_ESP32C3 board.

I'm guessing that there is a missing configuration of the ESP32 core clock divider/multiplier setting that didn't get adjusted with all of the other changes made by espressif in the 3.0.0 release.

I'm unaware of what version/variant of the ESP32 is on the "Sparkfun ESP32 THING".
Feel free to ask if you need details on any particulars I can provide.

**Comment by dfrodin** [comment]
This chunk of code was pulled out of the Arduino examples/eps32/serial/Serial_All_CPU_Freqs.ino produces different
results depending on which esp32 board library is used.

uint32_t Freq = getCpuFrequencyMhz();
Serial.print("CPU Freq = ");
Serial.print(Freq);
Serial.println(" MHz");
Freq = getXtalFrequencyMhz();
Serial.print("XTAL Freq = ");
Serial.print(Freq);
Serial.println(" MHz");
Freq = getApbFrequency();
Serial.print("APB Freq = ");
Serial.print(Freq);
Serial.println(" Hz");

For the 2.0.17 version it produces ...
CPU Freq = 240 MHz
XTAL Freq = 26 MHz
APB Freq = 80000000 Hz

For the 3.0.1 version it produces ...
CPU Freq = 240 MHz
XTAL Freq = 40 MHz
APB Freq = 80000000 Hz

I would guess that the XTAL frequency is a hardcoded value defined in the board code. And even though the 3.0.1 version reports the CPU Freq as 240MHz it might be 160MHz.

**Comment by PaulZC** [comment]
Hi Dave (@dfrodin ),

Many thanks for digging into this.

We haven't seen the same issue on other ESP32 boards - but they usually use ESP32 modules with the crystal built-in. On the Thing, the XTAL is 26MHz and is 'external' to the ESP32-D0WDQ6-V3 processor:

![image](https://github.com/sparkfun/ESP32_Thing_Plus/assets/5690545/d4ebd683-9270-4f19-92d7-9f8af4ad70ec)

I suspect v3.0.0 of the core isn't detecting the XTAL frequency correctly, or is defaulting to the wrong value.

This code is relevant:

https://github.com/espressif/esp-idf/blob/8760e6d2a7e19913bc40675dd71f374bcd51b0ae/components/esp_hw_support/port/esp32/rtc_clk.c#L547-L559

It might be possible to correct the XTAL frequency by calling ```rtc_clk_xtal_freq_update((rtc_xtal_freq_t)26);``` ?

I don't have a Thing here... Could you please set Core Debug Level to Verbose and give this a try:

```
#include "soc/rtc.h"

void setup() {
  delay(1000);

  rtc_clk_xtal_freq_update((rtc_xtal_freq_t)26);
  
  Serial.begin(115200);
  Serial.println("Hello world");
}

void loop() {
}
```

Best wishes,
Paul

**Comment by dfrodin** [comment]
Paul,
Thanks for your response.
I'm using Arduino IDE ver 1.8.19. The verbose options for it are for "compilation" and/or "upload".
Was the "set Core Debug Level to Verbose" request a setting in the ver 2.x IDE?

I added a call to getXtalFrequencyMhz() which shows the transition from 40MHz to 26Mhz. It had no impact on the
serial baud rate or the millis() timer.
If the rtc_xtal_freq gets updated, doesn't a call need to be made to do the calculations/configuration of the divider/multiplers to get to 240MHz from 26MHz rather than 40MHz?

**Comment by PaulZC** [comment]
Hi Dave,

The Verbose option is under Tools \ Core Debug Level (in the "Boards" section).

So, no magic wand... That's a shame. I tried the code on a ESP32 Thing Plus C and it didn't change the baud rate either... I was hoping it might work on the Thing, but I'm not very surprised it isn't... I'll take another look at this tomorrow. We might need to ask Espressif for advice and/or a fix.

More later,
Paul

**Comment by PaulZC** [comment]
Hi again Dave,

I think you're right about the divider (re)initialization. ```rtc_clk_cpu_freq_set_xtal();``` might be what we're looking for. It certainly changes the baud rate on the Thing Plus C. Please give it a go on your Thing.

```
#include "soc/rtc.h"

void setup() {
  delay(1000);

  rtc_clk_xtal_freq_update((rtc_xtal_freq_t)26);
  rtc_clk_cpu_freq_set_xtal();
  
  Serial.begin(115200);
  Serial.println("Hello world");
}

void loop() {
}
```

Best,
Paul

**Comment by dfrodin** [comment]
Paul,
You nailed it so go ahead and take the rest of the day off.

this ...
   rtc_clk_xtal_freq_update((rtc_xtal_freq_t)26);
   rtc_clk_cpu_freq_set_xtal();

produces this result...
  CPU Freq = 26 MHz
  XTAL Freq = 26 MHz
  APB Freq = 26000000 Hz

then...
   setCpuFrequencyMhz(240);

produces...
  CPU Freq = 240 MHz
 XTAL Freq = 26 MHz
 APB Freq = 80000000 Hz

with the 3 calls from above the baud rate is correct at 115200 and the millis() timer is dead on.

I guess espressif should be made aware that there's some sort of bug in their clock init code.
I'll add the xtal/clk init changes to my existing code and go on my merry way.
If I see any future updates from 3.0.1 version of the  espressif lib I'll remove the xtal/clk tweak to
see if it was fixed in the library.

Thanks for finding this work around for me.
Dave Frodin

**Comment by PaulZC** [comment]
Issue opened here: https://github.com/espressif/arduino-esp32/issues/9837

**Comment by PaulZC** [comment]
Resolved! Please see: https://github.com/espressif/arduino-esp32/pull/9844

I'll leave this open until the fix is built into a arduino-esp32 Release Candidate

**Comment by dfrodin** [comment]
PaulZC,
I've retested with the 3.0.2 version of the ESP32 library and everything is behaving correctly. Thanks for your efforts.

**Comment by PaulZC** [comment]
Thanks Dave. Closing...

**Comment by emilfihlman** [comment]
Is this supposed to be working now?
I'm using the latest nightly and esp32 3.0.5 and running into this.

**Comment by emilfihlman** [comment]
Initial findings:

So there was a patch, but a) it didn't patch esp32thing**_plus**, just esp32thing, ie esp32thing_plus is missing

`#define F_XTAL_MHZ 26  //SparkFun ESP32 Thing has 26MHz Crystal`
in variants/esp32thing_plus/pins_arduino.h

Secondly it still doesn't work, even though I've closed and opened and cleared /tmp/arduino etc many times for some reason and compiled and upload many times.

**Comment by emilfihlman** [comment]
According to the datasheet (ESP32-WROOM-32D), this device should have 40MHz crystal, yet it definitely outputs at 74880 when Serial.begin(115200) is set.

Even stranger: after upload the device outputs at 74880, but then on plug out and back in or pressing reset button results in the device outputting on 115200 :D

Even even stranger, the device also initially outputs on the correct frequency but then switches to the wrong one after _after_

The only code on the device is Arduino RMT.

**Comment by emilfihlman** [comment]
Since the issue was supposed to have been fixed at the espressif arduino repo, I'm putting everything in that issue there for now instead to all three places.

https://github.com/espressif/arduino-esp32/issues/9837

**Comment by emilfihlman** [comment]
Issue opened at https://github.com/espressif/arduino-esp32/issues/10388
